server:
  port: 8080

endpoints:
  shutdown:
    sensitive: false
    enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/pyxis
    username: root
    password: root
    max-active: 10
    initial-size: 5
    max-idle: 5
    min-idle: 1
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 15000
    min-evictable-idle-time-millis: 60000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate.ddl-auto: validate

flyway:
  enabled: true
  locations: filesystem:src/main/resources/db/migration
  baseline-on-migrate: true